### PR TITLE
Wrap all tests in a CLFFT.jl testset

### PR DESCRIPTION
**Pull request by juliohm**
So that all tests are executed even if a test set fails.

### CODE REVIEW

**Comment by juliohm** [comment]
The diff is not easy to read, I just wrapped the existing test sets into a big `CLFFT.jl` testset.

**Comment by juliohm** [comment]
Could you please review and merge? :)

**Comment by SimonDanisch** [comment]
Can you rebase on master, so that we have gitlab ci?

**Comment by juliohm** [comment]
Done :+1: let me know if anything is missing.

**Comment by SimonDanisch** [comment]
Thanks! Not sure why gitlab doesn't want to test this, but maybe because its from before!?

**Pull request merged**
