### PR TITLE
Fixes for Julia v1.0

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by juliohm** [comment]
Appreciate if someone can review and merge these changes. They are all trivial syntax changes.

**Comment by juliohm** [comment]
@vchuravy could you please take a look at this?

**Comment by juliohm** [comment]
Anyone could please review this PR? The tests are passing since October last year.

**Comment by dfdx** [comment]
I was under impression that all Cu* and CL* stuff has been moved to CuArrays and CLArrays respectively. Now it seems true for CUDA, but not for OpenCL, so sure, let's merge it! 

Thanks @juliohm for this update and your patience :)

**Pull request merged**
