### PR TITLE
Fix #8 - Correct list of supported radices in FFT plans

### LINKED ISSUE #8: Incorrect list of supported radices
The list of supported radices changes depending on the clFFT release. Old releases support powers of 2, 3 and 5. In `v2.8.0` support was added for powers of 7. In `v2.12.0` powers of 11 and 13 are also supported. Please check the release notes at https://github.com/clMathLibraries/clFFT/releases.

The [checks](https://github.com/JuliaGPU/CLFFT.jl/blob/master/src/CLFFT.jl#L80-L124) being performed in `CLFFT.jl` doesn't take versions into account and I am getting error messages for valid input dimensions.

Could you please fix the issue?

### PR DESCRIPTION
**Pull request by juliohm**
Please merge this PR with corrections for different versions of clFFT.

### CODE REVIEW

**Comment by juliohm** [comment]
The tests are "passing" now in Travis, can someone please merge this?

**Comment by dfdx** [comment]
> The tests are "passing" now in Travis, can someone please merge this?

Still not passing :) I don't think it's related to your changes, but it would be nice to fix it anyway. I'll a look at it in the evening, but maybe you already have a suggestion how to fix job in Travis?

**Comment by juliohm** [comment]
@dfdx meanwhile could you please merge this PR? Since it is not related to the build failure, it could be in master already.

I am still on the process of setting up Travis with OpenCL for my own packages :blush: , cannot help much with the build.

**Comment by juliohm** [comment]
@dfdx could you please add a version tag for this change?

**Comment by dfdx** [comment]
@juliohm I'm currently working on fixing tests on Travis and have some progress in it, so I'd prefer to finish it before tagging a new version. Is it a blocker for you? If so, I can merge partial solution that at least solves building issue.

**Comment by juliohm** [comment]
Not a rush, I'm also busy with other things, whenever you have time.

Best,
-Júlio

**Pull request merged**
